import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subnets: ['latin'], weight: ['400', '500', '600', '700']
});
const ovo = Ovo({
  subsets: ['latin'], weight: ['400']
})

export const metadata = {
  title: "Tran Tan Dat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} ${ovo.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
